<div class="overlay"></div>
<div class="action_container buy">
    <div class="request_container">
        <h1>Buy</h1>
        <div class="action request clearfix">
            <form method="post" enctype="application/x-www-form-urlencoded">
                <div class="left">
                    <div class="label select">
                        <label for="location">Property Type</label>
                        <select data-selectivity="true" name="location" id="location">
                            <option value="">Appartment</option>
                            <option value="">Villa</option>
                            <option value="">Duplex</option>
                            <option value="">Challet</option>
                        </select>
                    </div>
                    <div class="label">
                        <label for="budegt">Your Budget (EGP) <span class="red">*</span></label>
                        <input required type="text" name="budegt" id="budegt" placeholder="Ex: 2,000,000">
                    </div>
                    <div class="label select">
                        <label for="location">When do you need to buy?</label>
                        <select data-selectivity="true" name="location" id="location">
                            <option value="">Immediately</option>
                            <option value="">1 Month</option>
                            <option value="">3 Month</option>
                            <option value="">6 Month</option>
                        </select>
                    </div>
                </div>
                <div class="right">
                    <div class="label">
                        <label for="phone">Tell us more (optional) <span class="red">*</span></label>
                        <textarea placeholder="Area, number of rooms, ... etc" name="" id="" cols="30" rows="10"></textarea>
                        <input type="submit" name="submit" value="Submit">
                    </div>
                </div>
            </form>
        </div>
        <div class="action register"></div>
        <div class="action thank_you"></div>
    </div>
    <div class="steps">
        <div class="step selected"></div>
        <div class="step"></div>
        <div class="step"></div>
    </div>
</div>
<div class="action_container sell">
    <div class="request_container">
        <div class="action request clearfix">
            <form method="post" enctype="application/x-www-form-urlencoded">
                <div class="left">
                    <div class="label select">
                        <label for="location">Property Type</label>
                        <select data-selectivity="true" name="location" id="location">
                            <option value="">Appartment</option>
                            <option value="">Villa</option>
                            <option value="">Duplex</option>
                            <option value="">Challet</option>
                        </select>
                    </div>
                    <div class="label">
                        <label for="price">Price (EGP) <span class="red">*</span></label>
                        <input required type="text" name="price" id="price" placeholder="Ex: 2,000,000">
                    </div>
                    <div class="label select">
                        <label for="location">When do you need to sell?</label>
                        <select data-selectivity="true" name="location" id="location">
                            <option value="">Immediately</option>
                            <option value="">1 Month</option>
                            <option value="">3 Month</option>
                            <option value="">6 Month</option>
                        </select>
                    </div>
                </div>
                <div class="right">
                    <div class="label">
                        <label for="phone">Tell us more (optional) <span class="red">*</span></label>
                        <textarea placeholder="Area, number of rooms, ... etc" name="" id="" cols="30" rows="10"></textarea>
                        <input class="orange" type="submit" name="submit" value="Submit">
                    </div>
                </div>
            </form>
        </div>
        <div class="action register"></div>
        <div class="action thank_you"></div>
    </div>
    <div class="steps">
        <div class="step selected"></div>
        <div class="step"></div>
        <div class="step"></div>
    </div>
</div>
<div class="action_container valuation">
    <div class="request_container">
        <div class="action request clearfix">
            <form method="post" enctype="application/x-www-form-urlencoded">
                <div class="left">
                    <div class="label select">
                        <label for="location">Property Type</label>
                        <select data-selectivity="true" name="location" id="location">
                            <option value="">Appartment</option>
                            <option value="">Villa</option>
                            <option value="">Duplex</option>
                            <option value="">Challet</option>
                        </select>
                    </div>
                    <div class="label">
                        <label for="area">Area <span class="red">*</span></label>
                        <input required type="text" name="area" id="area" placeholder="Ex: 297m">
                    </div>
                    <div class="label">
                        <label for="area">Detailed address <span class="red">*</span></label>
                        <input required type="text" name="area" id="area" placeholder="Ex: Cairo, Zamalek">
                    </div>
                </div>
                <div class="right">
                    <div class="label">
                        <label for="phone">Tell us more (optional) <span class="red">*</span></label>
                        <textarea placeholder="Floor NO, number of rooms, ... etc" name="" id="" cols="30" rows="10"></textarea>
                        <input class="brown" type="submit" name="submit" value="Submit">
                    </div>
                </div>
            </form>
        </div>
        <div class="action register"></div>
        <div class="action thank_you"></div>
    </div>
    <div class="steps">
        <div class="step selected"></div>
        <div class="step"></div>
        <div class="step"></div>
    </div>
</div>