<section class="home_slide_template">
    <div class="home_slide_content_wrapper">
        <a href="" class="mobile_menu"><i class="fa fa-bars"></i></a>
        <div class="overlay"></div>
        <ul class="mobile_menu">
            <a href="" class="close"><i class="fa fa-times"></i></a>
            <li><a href="/"><i class="fa fa-home"></i>Home</a></li>
            <li><a href="/buy"><i class="fa fa-shopping-bag"></i>Buy</a></li>
            <li><a href="/sell"><i class="fa fa-tag"></i>Sell</a></li>
            <li><a href="/agents"><i class="fa fa-group"></i>Our Agents</a></li>
            <li><a href="/howitworks"><i class="fa fa-question-circle"></i>How it works?</a></li>
            <li><a href="/auth/login"><i class="fa fa-sign-in"></i>Login</a></li>
            <li><a href="/auth/register"><i class="fa fa-edit"></i>Register</a></li>
            <li><a href="javascript:;"><i class="fa fa-globe"></i>عربي</a></li>
        </ul>
        <div class="logo"><a href="/"><img src="/img/logo_colored.png"></a></div>
        <h1>Egypt</h1>
        <div class="authentication">
            <a class="login" href="/auth/login">Login</a>
            <span>Or</span>
            <a class="register" href="/auth/register">Sign Up</a>
        </div>
        <div class="head_tool_bar">
            <ul>
                <li><a href="/buy">Buy</a></li>
                <li><a href="/sell">Sell</a></li>
                <li><a href="/agents">Our Agents</a></li>
                <li><a href="/howitworks">How it works?</a></li>
                <li><a href="javascript:;">عربي</a></li>
            </ul>
        </div>
    </div>
</section>